# Generated by Django 3.2.3 on 2021-06-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombre', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
    ]
