# Generated by Django 3.2.3 on 2021-06-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0002_peluquero_producto_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(null=True, upload_to='media/productos'),
        ),
    ]
