# Generated by Django 3.2.3 on 2021-06-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0003_alter_producto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='foto',
            field=models.ImageField(null=True, upload_to='media/sucursal'),
        ),
    ]
