# Generated by Django 3.2.3 on 2021-06-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0004_sucursal_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='correo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='horarios',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
