# Generated by Django 3.2.3 on 2021-06-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0005_auto_20210616_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='mapa',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
