# Generated by Django 3.2.3 on 2021-06-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0006_sucursal_mapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='peluquero',
            name='apodo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='peluquero',
            name='foto',
            field=models.ImageField(null=True, upload_to='media/peluqueros'),
        ),
    ]
