# Generated by Django 3.2.3 on 2021-06-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0007_auto_20210616_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media/categoria'),
        ),
    ]
