# Generated by Django 3.2.3 on 2021-06-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0008_categoria_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id_auto_inc', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('foto', models.ImageField(null=True, upload_to='media/cortes')),
                ('publicado', models.BooleanField(default=False)),
            ],
        ),
    ]
