# Generated by Django 3.2.3 on 2021-06-25 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0009_corte'),
    ]

    operations = [
        migrations.AddField(
            model_name='corte',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BS.categoria'),
        ),
        migrations.AddField(
            model_name='corte',
            name='peluquero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BS.peluquero'),
        ),
    ]
