# Generated by Django 3.2.3 on 2021-06-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0010_auto_20210625_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='corte',
            name='comentario',
            field=models.TextField(null=True),
        ),
    ]
