# Generated by Django 3.2.3 on 2021-06-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0011_corte_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='corte',
            name='usuario',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='peluquero',
            name='usuario',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='usuario',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='usuario',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
