# Generated by Django 3.2.3 on 2021-06-27 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0012_auto_20210627_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corte',
            name='usuario',
        ),
    ]
