# Generated by Django 3.2.3 on 2021-06-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS', '0013_remove_corte_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='peluquero',
            name='comentario',
            field=models.TextField(default='Sin comentarios'),
        ),
        migrations.AddField(
            model_name='producto',
            name='comentario',
            field=models.TextField(default='Sin comentarios'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='comentario',
            field=models.TextField(default='Sin comentarios'),
        ),
    ]
